const newsEndpoints = [
  {
    method: 'GET',
    path: '/api/news',
    description: 'Lấy danh sách tất cả tin tức',
    fullDescription: 'Trả về danh sách tất cả tin tức (bao gồm cả trạng thái `show` và `hidden`), sắp xếp theo ngày xuất bản (`publishedAt`) giảm dần. Endpoint này dành cho admin hoặc hệ thống để quản lý tin tức, không yêu cầu xác thực, có thể truy cập công khai.',
    auth: {
      required: false,
      description: 'Không yêu cầu token. Endpoint này có thể truy cập công khai.',
    },
    parameters: [],
    response: {
      status: 200,
      description: 'Danh sách tin tức',
      example: [
        {
          _id: '60d5f8e9b1a2b4f8e8f9e2c6',
          title: 'Tin tức mới nhất về Pure-Botanica',
          slug: 'tin-tuc-moi-nhat-ve-pure-botanica',
          thumbnailUrl: 'https://res.cloudinary.com/your_cloud_name/image/upload/thumbnail1.jpg',
          thumbnailCaption: 'Hình ảnh tin tức',
          publishedAt: '2025-07-17T12:06:00.000Z',
          views: 100,
          status: 'show',
          content: '<p>Nội dung chi tiết về tin tức...</p><img src="https://res.cloudinary.com/your_cloud_name/image/upload/news_content/123e4567-e89b-12d3-a456-426614174000.jpg" alt="skincare">',
          contentImageUrls: ['https://res.cloudinary.com/your_cloud_name/image/upload/news_content/123e4567-e89b-12d3-a456-426614174000.jpg'],
          createdAt: '2025-07-17T12:06:00.000Z',
          updatedAt: '2025-07-17T12:06:00.000Z',
        },
      ],
    },
    errorResponses: [
      { status: 404, description: 'Không tìm thấy tin tức nào' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database' },
    ],
  },
  {
    method: 'GET',
    path: '/api/news/:identifier',
    description: 'Lấy chi tiết tin tức',
    fullDescription: 'Lấy chi tiết một tin tức dựa trên ObjectId hoặc slug. Nếu không có header Authorization (người dùng thường), lượt xem (`views`) sẽ tăng. Nếu có token admin, lượt xem không tăng. Không yêu cầu xác thực cho người dùng thường.',
    auth: {
      required: false,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT tùy chọn. Nếu có token admin, lượt xem không tăng. Nếu không có token, lượt xem tăng lên.',
    },
    parameters: [
      {
        name: 'identifier',
        type: 'string',
        description: 'ObjectId hoặc slug của tin tức',
        required: true,
        in: 'path',
      },
    ],
    response: {
      status: 200,
      description: 'Chi tiết tin tức',
      example: {
        _id: '60d5f8e9b1a2b4f8e8f9e2c6',
        title: 'Tin tức mới nhất về Pure-Botanica',
        slug: 'tin-tuc-moi-nhat-ve-pure-botanica',
        thumbnailUrl: 'https://res.cloudinary.com/your_cloud_name/image/upload/thumbnail1.jpg',
        thumbnailCaption: 'Hình ảnh tin tức',
        publishedAt: '2025-07-17T12:06:00.000Z',
        views: 101,
        status: 'show',
        content: '<p>Nội dung chi tiết về tin tức...</p><img src="https://res.cloudinary.com/your_cloud_name/image/upload/news_content/123e4567-e89b-12d3-a456-426614174000.jpg" alt="skincare">',
        contentImageUrls: ['https://res.cloudinary.com/your_cloud_name/image/upload/news_content/123e4567-e89b-12d3-a456-426614174000.jpg'],
        createdAt: '2025-07-17T12:06:00.000Z',
        updatedAt: '2025-07-17T12:06:00.000Z',
      },
    },
    errorResponses: [
      { status: 404, description: 'Không tìm thấy tin tức' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database' },
    ],
  },
  {
    method: 'GET',
    path: '/api/news/hottest',
    description: 'Lấy danh sách tin tức hot',
    fullDescription: 'Trả về danh sách tin tức có trạng thái `show`, sắp xếp theo lượt xem (`views`) giảm dần. Hỗ trợ query `limit` để giới hạn số lượng tin tức. Không yêu cầu xác thực, có thể truy cập công khai.',
    auth: {
      required: false,
      description: 'Không yêu cầu token. Endpoint này có thể truy cập công khai.',
    },
    parameters: [
      {
        name: 'limit',
        type: 'number',
        description: 'Số lượng tin tức tối đa trả về (mặc định: tất cả)',
        required: false,
        in: 'query',
      },
    ],
    response: {
      status: 200,
      description: 'Danh sách tin tức hot',
      example: {
        message: 'Lấy danh sách bài đăng hot thành công',
        news: [
          {
            _id: '60d5f8e9b1a2b4f8e8f9e2c6',
            title: 'Tin tức mới nhất về Pure-Botanica',
            slug: 'tin-tuc-moi-nhat-ve-pure-botanica',
            thumbnailUrl: 'https://res.cloudinary.com/your_cloud_name/image/upload/thumbnail1.jpg',
            thumbnailCaption: 'Hình ảnh tin tức',
            publishedAt: '2025-07-17T12:06:00.000Z',
            views: 100,
            status: 'show',
            content: '<p>Nội dung chi tiết về tin tức...</p><img src="https://res.cloudinary.com/your_cloud_name/image/upload/news_content/123e4567-e89b-12d3-a456-426614174000.jpg" alt="skincare">',
            contentImageUrls: ['https://res.cloudinary.com/your_cloud_name/image/upload/news_content/123e4567-e89b-12d3-a456-426614174000.jpg'],
            createdAt: '2025-07-17T12:06:00.000Z',
            updatedAt: '2025-07-17T12:06:00.000Z',
          },
        ],
      },
    },
    errorResponses: [
      { status: 404, description: 'Không tìm thấy bài đăng nào' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database' },
    ],
  },
  {
    method: 'POST',
    path: '/api/news',
    description: 'Tạo tin tức mới',
    fullDescription: 'Tạo một tin tức mới với tiêu đề, nội dung (HTML hợp lệ, có thể chứa hình ảnh Base64), và thumbnail bắt buộc. Hình ảnh Base64 trong `content` (e.g., `<img src="data:image/jpeg;base64,...">`) và file `contentImages` được tải lên Cloudinary, cập nhật `src` thành URL Cloudinary và lưu vào `contentImageUrls`. Thumbnail được tải lên Cloudinary. Slug được tự động tạo nếu không cung cấp. Yêu cầu quyền admin thông qua token JWT. Dữ liệu gửi qua `multipart/form-data`.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'title',
        type: 'string',
        description: 'Tiêu đề tin tức',
        required: true,
        in: 'body',
      },
      {
        name: 'content',
        type: 'string',
        description: 'Nội dung tin tức (HTML hợp lệ, hỗ trợ `<img>` với Base64 URLs `data:image/jpeg;base64,...`, `data:image/png;base64,...`, `data:image/gif;base64,...`, hoặc `data:image/webp;base64,...`)',
        required: true,
        in: 'body',
      },
      {
        name: 'thumbnail',
        type: 'file',
        description: 'File hình ảnh thumbnail (jpg, jpeg, png, gif, webp, svg; tối đa 20MB)',
        required: true,
        in: 'formData',
      },
      {
        name: 'contentImages',
        type: 'file',
        description: 'Các file hình ảnh nội dung (jpg, jpeg, png, gif, webp, svg; tối đa 20MB mỗi file, tùy chọn)',
        required: false,
        in: 'formData',
      },
      {
        name: 'slug',
        type: 'string',
        description: 'Slug của tin tức (tùy chọn, tự động tạo nếu không cung cấp)',
        required: false,
        in: 'body',
      },
      {
        name: 'thumbnailCaption',
        type: 'string',
        description: 'Chú thích cho thumbnail (tùy chọn)',
        required: false,
        in: 'body',
      },
      {
        name: 'publishedAt',
        type: 'string',
        description: 'Ngày xuất bản (định dạng ISO, mặc định: hiện tại)',
        required: false,
        in: 'body',
      },
      {
        name: 'views',
        type: 'number',
        description: 'Số lượt xem ban đầu (mặc định: 0, phải không âm)',
        required: false,
        in: 'body',
      },
      {
        name: 'status',
        type: 'string',
        description: 'Trạng thái tin tức (`show` hoặc `hidden`, mặc định: `show`)',
        required: false,
        in: 'body',
      },
    ],
    requestExample: {
      headers: { Authorization: 'Bearer <token>', 'Content-Type': 'multipart/form-data' },
      body: {
        title: 'Tin tức mới nhất về Pure-Botanica',
        content: '<p>Nội dung chi tiết về tin tức...</p><img src="data:image/jpeg;base64,/9j/4AAQSkZ..." alt="skincare">',
        slug: 'tin-tuc-moi-nhat',
        thumbnailCaption: 'Hình ảnh tin tức',
        publishedAt: '2025-07-17T12:06:00.000Z',
        views: 0,
        status: 'show',
      },
      files: {
        thumbnail: 'thumbnail1.jpg',
        contentImages: ['content1.jpg', 'content2.jpg'],
      },
    },
    response: {
      status: 201,
      description: 'Tạo tin tức thành công',
      example: {
        message: 'Tạo tin tức thành công',
        news: {
          _id: '60d5f8e9b1a2b4f8e8f9e2c6',
          title: 'Tin tức mới nhất về Pure-Botanica',
          slug: 'tin-tuc-moi-nhat',
          thumbnailUrl: 'https://res.cloudinary.com/your_cloud_name/image/upload/thumbnail1.jpg',
          thumbnailCaption: 'Hình ảnh tin tức',
          publishedAt: '2025-07-17T12:06:00.000Z',
          views: 0,
          status: 'show',
          content: '<p>Nội dung chi tiết về tin tức...</p><img src="https://res.cloudinary.com/your_cloud_name/image/upload/news_content/123e4567-e89b-12d3-a456-426614174000.jpg" alt="skincare">',
          contentImageUrls: [
            'https://res.cloudinary.com/your_cloud_name/image/upload/news_content/123e4567-e89b-12d3-a456-426614174000.jpg',
            'https://res.cloudinary.com/your_cloud_name/image/upload/news_content/123e4567-e89b-12d3-a456-426614174001.jpg',
          ],
          createdAt: '2025-07-17T12:06:00.000Z',
          updatedAt: '2025-07-17T12:06:00.000Z',
        },
      },
    },
    errorResponses: [
      { status: 400, description: 'Thiếu các trường bắt buộc: title, content, hoặc thumbnail' },
      { status: 400, description: 'Trùng lặp slug' },
      { status: 400, description: 'Nội dung HTML không hợp lệ' },
      { status: 400, description: 'Data URL không hợp lệ hoặc loại hình ảnh không được hỗ trợ (chỉ hỗ trợ jpeg, png, gif, webp)' },
      { status: 400, description: 'Chỉ hỗ trợ file ảnh (jpg, jpeg, png, gif, webp, svg) cho thumbnail hoặc contentImages' },
      { status: 400, description: 'Kích thước hình ảnh vượt quá 20MB' },
      { status: 400, description: 'Trạng thái không hợp lệ, chỉ được là `show` hoặc `hidden`' },
      { status: 400, description: 'Số lượt xem phải không âm' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database hoặc Cloudinary' },
    ],
  },
  {
    method: 'PUT',
    path: '/api/news/:identifier',
    description: 'Cập nhật tin tức',
    fullDescription: 'Cập nhật thông tin tin tức dựa trên ObjectId hoặc slug. Hỗ trợ cập nhật thumbnail và nội dung (HTML hợp lệ, có thể chứa hình ảnh Base64). Hình ảnh Base64 trong `content` và file `contentImages` được tải lên Cloudinary, cập nhật `src` thành URL Cloudinary và lưu vào `contentImageUrls`. Thumbnail được tải lên Cloudinary nếu cung cấp. Slug được tự động tạo nếu cung cấp giá trị mới. Yêu cầu quyền admin thông qua token JWT. Dữ liệu gửi qua `multipart/form-data`.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'identifier',
        type: 'string',
        description: 'ObjectId hoặc slug của tin tức',
        required: true,
        in: 'path',
      },
      {
        name: 'title',
        type: 'string',
        description: 'Tiêu đề tin tức mới',
        required: false,
        in: 'body',
      },
      {
        name: 'content',
        type: 'string',
        description: 'Nội dung tin tức mới (HTML hợp lệ, hỗ trợ `<img>` với Base64 URLs `data:image/jpeg;base64,...`, `data:image/png;base64,...`, `data:image/gif;base64,...`, hoặc `data:image/webp;base64,...`)',
        required: false,
        in: 'body',
      },
      {
        name: 'thumbnail',
        type: 'file',
        description: 'File hình ảnh thumbnail mới (jpg, jpeg, png, gif, webp, svg; tối đa 20MB)',
        required: false,
        in: 'formData',
      },
      {
        name: 'contentImages',
        type: 'file',
        description: 'Các file hình ảnh nội dung mới (jpg, jpeg, png, gif, webp, svg; tối đa 20MB mỗi file, tùy chọn)',
        required: false,
        in: 'formData',
      },
      {
        name: 'slug',
        type: 'string',
        description: 'Slug mới (tùy chọn, tự động tạo nếu cung cấp)',
        required: false,
        in: 'body',
      },
      {
        name: 'thumbnailCaption',
        type: 'string',
        description: 'Chú thích mới cho thumbnail',
        required: false,
        in: 'body',
      },
      {
        name: 'publishedAt',
        type: 'string',
        description: 'Ngày xuất bản mới (định dạng ISO)',
        required: false,
        in: 'body',
      },
      {
        name: 'views',
        type: 'number',
        description: 'Số lượt xem mới (phải không âm)',
        required: false,
        in: 'body',
      },
      {
        name: 'status',
        type: 'string',
        description: 'Trạng thái mới (`show` hoặc `hidden`)',
        required: false,
        in: 'body',
      },
    ],
    requestExample: {
      headers: { Authorization: 'Bearer <token>', 'Content-Type': 'multipart/form-data' },
      body: {
        title: 'Tin tức cập nhật về Pure-Botanica',
        content: '<p>Nội dung cập nhật...</p><img src="data:image/jpeg;base64,/9j/4AAQSkZ..." alt="skincare">',
        slug: 'tin-tuc-cap-nhat',
        thumbnailCaption: 'Hình ảnh mới',
        status: 'hidden',
      },
      files: {
        thumbnail: 'thumbnail2.jpg',
        contentImages: ['content3.jpg'],
      },
    },
    response: {
      status: 200,
      description: 'Cập nhật tin tức thành công',
      example: {
        message: 'Cập nhật tin tức thành công',
        news: {
          _id: '60d5f8e9b1a2b4f8e8f9e2c6',
          title: 'Tin tức cập nhật về Pure-Botanica',
          slug: 'tin-tuc-cap-nhat',
          thumbnailUrl: 'https://res.cloudinary.com/your_cloud_name/image/upload/thumbnail2.jpg',
          thumbnailCaption: 'Hình ảnh mới',
          publishedAt: '2025-07-17T12:06:00.000Z',
          views: 100,
          status: 'hidden',
          content: '<p>Nội dung cập nhật...</p><img src="https://res.cloudinary.com/your_cloud_name/image/upload/news_content/123e4567-e89b-12d3-a456-426614174001.jpg" alt="skincare">',
          contentImageUrls: ['https://res.cloudinary.com/your_cloud_name/image/upload/news_content/123e4567-e89b-12d3-a456-426614174001.jpg'],
          createdAt: '2025-07-17T12:06:00.000Z',
          updatedAt: '2025-07-17T12:06:00.000Z',
        },
      },
    },
    errorResponses: [
      { status: 400, description: 'Trùng lặp slug' },
      { status: 400, description: 'Nội dung HTML không hợp lệ' },
      { status: 400, description: 'Data URL không hợp lệ hoặc loại hình ảnh không được hỗ trợ (chỉ hỗ trợ jpeg, png, gif, webp)' },
      { status: 400, description: 'Chỉ hỗ trợ file ảnh (jpg, jpeg, png, gif, webp, svg) cho thumbnail hoặc contentImages' },
      { status: 400, description: 'Kích thước hình ảnh vượt quá 20MB' },
      { status: 400, description: 'Trạng thái không hợp lệ, chỉ được là `show` hoặc `hidden`' },
      { status: 400, description: 'Số lượt xem phải không âm' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 404, description: 'Không tìm thấy tin tức để cập nhật' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database hoặc Cloudinary' },
    ],
  },
  {
    method: 'DELETE',
    path: '/api/news/:identifier',
    description: 'Xóa tin tức',
    fullDescription: 'Xóa một tin tức dựa trên ObjectId hoặc slug. Hình ảnh thumbnail và nội dung trên Cloudinary không được xóa tự động (quản lý bởi Cloudinary garbage collection). Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'identifier',
        type: 'string',
        description: 'ObjectId hoặc slug của tin tức',
        required: true,
        in: 'path',
      },
    ],
    response: {
      status: 200,
      description: 'Xóa tin tức thành công',
      example: {
        message: 'Xóa tin tức thành công',
      },
    },
    errorResponses: [
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 404, description: 'Không tìm thấy tin tức để xóa' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database' },
    ],
  },
  {
    method: 'PUT',
    path: '/api/news/:identifier/toggle-visibility',
    description: 'Chuyển đổi trạng thái hiển thị tin tức',
    fullDescription: 'Chuyển đổi trạng thái của tin tức giữa `show` và `hidden` dựa trên ObjectId hoặc slug. Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'identifier',
        type: 'string',
        description: 'ObjectId hoặc slug của tin tức',
        required: true,
        in: 'path',
      },
    ],
    response: {
      status: 200,
      description: 'Chuyển đổi trạng thái hiển thị thành công',
      example: {
        message: 'Tin tức đã được ẩn',
        news: {
          _id: '60d5f8e9b1a2b4f8e8f9e2c6',
          title: 'Tin tức mới nhất về Pure-Botanica',
          slug: 'tin-tuc-moi-nhat',
          thumbnailUrl: 'https://res.cloudinary.com/your_cloud_name/image/upload/thumbnail1.jpg',
          thumbnailCaption: 'Hình ảnh tin tức',
          publishedAt: '2025-07-17T12:06:00.000Z',
          views: 100,
          status: 'hidden',
          content: '<p>Nội dung chi tiết về tin tức...</p><img src="https://res.cloudinary.com/your_cloud_name/image/upload/news_content/123e4567-e89b-12d3-a456-426614174000.jpg" alt="skincare">',
          contentImageUrls: ['https://res.cloudinary.com/your_cloud_name/image/upload/news_content/123e4567-e89b-12d3-a456-426614174000.jpg'],
          createdAt: '2025-07-17T12:06:00.000Z',
          updatedAt: '2025-07-17T12:06:00.000Z',
        },
      },
    },
    errorResponses: [
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 404, description: 'Không tìm thấy tin tức' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database' },
    ],
  },
];

export default newsEndpoints;