const orderEndpoints = [
  {
    method: 'GET',
    path: '/api/orders/admin/all',
    description: 'Lấy tất cả đơn hàng (admin)',
    fullDescription: 'Trả về danh sách tất cả đơn hàng trong hệ thống, sắp xếp theo ID (`_id`) giảm dần. Bao gồm thông tin sản phẩm (`items.product`) và người dùng (`user`) được populate. Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [],
    response: {
      status: 200,
      description: 'Danh sách tất cả đơn hàng',
      example: [
        {
          _id: '60d5f8e9b1a2b4f8e8f9e2c7',
          user: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b0',
            username: 'user1',
            email: 'user1@example.com',
          },
          items: [
            {
              product: {
                _id: '60d5f8e9b1a2b4f8e8f9e2b1',
                name: 'Sản phẩm A',
                price: 100000,
                image: 'https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg',
              },
              optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
              quantity: 2,
              images: ['https://res.cloudinary.com/your_cloud_name/image/upload/image1.jpg'],
            },
          ],
          subtotal: 200000,
          discount: 0,
          total: 200000,
          coupon: null,
          address: {
            addressLine: '123 Đường Láng',
            ward: 'Phường 1',
            district: 'Quận 1',
            cityOrProvince: 'TP.HCM',
          },
          sdt: '0123456789',
          paymentMethod: 'cod',
          paymentStatus: 'pending',
          shippingStatus: 'pending',
          returnStatus: 'none',
          returnRequestDate: null,
          returnReason: null,
          returnImages: [],
          returnVideos: [],
          note: 'Giao hàng nhanh',
          cancelReason: null,
          cancelNote: null,
          cancelledAt: null,
          cancelledBy: null,
          failReason: null,
          confirmedAt: null,
          createdAt: '2025-07-09T10:18:00Z',
          updatedAt: '2025-07-09T10:18:00Z',
        },
      ],
    },
    errorResponses: [
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database hoặc lỗi populate' },
    ],
  },
  {
    method: 'GET',
    path: '/api/orders/admin/user/:userId',
    description: 'Lấy đơn hàng theo người dùng (admin)',
    fullDescription: 'Trả về danh sách đơn hàng của một người dùng cụ thể dựa trên `userId`, sắp xếp theo ID (`_id`) giảm dần. Bao gồm thông tin sản phẩm (`items.product`) và người dùng (`user`) được populate. Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'userId',
        type: 'string',
        description: 'ObjectId của người dùng',
        required: true,
        in: 'path',
      },
    ],
    response: {
      status: 200,
      description: 'Danh sách đơn hàng của người dùng',
      example: [
        {
          _id: '60d5f8e9b1a2b4f8e8f9e2c7',
          user: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b0',
            username: 'user1',
            email: 'user1@example.com',
          },
          items: [
            {
              product: {
                _id: '60d5f8e9b1a2b4f8e8f9e2b1',
                name: 'Sản phẩm A',
                price: 100000,
                image: 'https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg',
              },
              optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
              quantity: 2,
              images: ['https://res.cloudinary.com/your_cloud_name/image/upload/image1.jpg'],
            },
          ],
          subtotal: 200000,
          discount: 0,
          total: 200000,
          coupon: null,
          address: {
            addressLine: '123 Đường Láng',
            ward: 'Phường 1',
            district: 'Quận 1',
            cityOrProvince: 'TP.HCM',
          },
          sdt: '0123456789',
          paymentMethod: 'cod',
          paymentStatus: 'pending',
          shippingStatus: 'pending',
          returnStatus: 'none',
          returnRequestDate: null,
          returnReason: null,
          returnImages: [],
          returnVideos: [],
          note: 'Giao hàng nhanh',
          cancelReason: null,
          cancelNote: null,
          cancelledAt: null,
          cancelledBy: null,
          failReason: null,
          confirmedAt: null,
          createdAt: '2025-07-09T10:18:00Z',
          updatedAt: '2025-07-09T10:18:00Z',
        },
      ],
    },
    errorResponses: [
      { status: 400, description: 'Thiếu userId hoặc userId không hợp lệ' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 404, description: 'Người dùng không tồn tại' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database hoặc lỗi populate' },
    ],
  },
  {
    method: 'GET',
    path: '/api/orders/admin/order/:orderId',
    description: 'Lấy chi tiết đơn hàng (admin)',
    fullDescription: 'Trả về chi tiết một đơn hàng dựa trên `orderId`, bao gồm thông tin sản phẩm (`items.product`) và người dùng (`user`) được populate. Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'orderId',
        type: 'string',
        description: 'ObjectId của đơn hàng',
        required: true,
        in: 'path',
      },
    ],
    response: {
      status: 200,
      description: 'Chi tiết đơn hàng',
      example: {
        _id: '60d5f8e9b1a2b4f8e8f9e2c7',
        user: {
          _id: '60d5f8e9b1a2b4f8e8f9e2b0',
          username: 'user1',
          email: 'user1@example.com',
        },
        items: [
          {
            product: {
              _id: '60d5f8e9b1a2b4f8e8f9e2b1',
              name: 'Sản phẩm A',
              price: 100000,
              image: 'https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg',
            },
            optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
            quantity: 2,
            images: ['https://res.cloudinary.com/your_cloud_name/image/upload/image1.jpg'],
          },
        ],
        subtotal: 200000,
        discount: 0,
        total: 200000,
        coupon: null,
        address: {
          addressLine: '123 Đường Láng',
          ward: 'Phường 1',
          districtទ: 'Quận 1',
          cityOrProvince: 'TP.HCM',
        },
        sdt: '0123456789',
        paymentMethod: 'cod',
        paymentStatus: 'pending',
        shippingStatus: 'pending',
        returnStatus: 'none',
        returnRequestDate: null,
        returnReason: null,
        returnImages: [],
        returnVideos: [],
        note: 'Giao hàng nhanh',
        cancelReason: null,
        cancelNote: null,
        cancelledAt: null,
        cancelledBy: null,
        failReason: null,
        confirmedAt: null,
        createdAt: '2025-07-09T10:18:00Z',
        updatedAt: '2025-07-09T10:18:00Z',
      },
    },
    errorResponses: [
      { status: 400, description: 'Thiếu orderId hoặc orderId không hợp lệ' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 404, description: 'Không tìm thấy đơn hàng' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database hoặc lỗi populate' },
    ],
  },
  {
    method: 'GET',
    path: '/api/orders/admin/failed',
    description: 'Lấy danh sách đơn hàng giao thất bại (admin)',
    fullDescription: 'Trả về danh sách các đơn hàng có trạng thái vận chuyển (`shippingStatus`) là `failed`, sắp xếp theo thời gian cập nhật (`updatedAt`) giảm dần. Bao gồm thông tin sản phẩm (`items.product`) và người dùng (`user`) được populate. Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [],
    response: {
      status: 200,
      description: 'Danh sách đơn hàng giao thất bại',
      example: [
        {
          _id: '60d5f8e9b1a2b4f8e8f9e2c8',
          user: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b0',
            username: 'user1',
            email: 'user1@example.com',
          },
          items: [
            {
              product: {
                _id: '60d5f8e9b1a2b4f8e8f9e2b1',
                name: 'Sản phẩm A',
                price: 100000,
                image: 'https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg',
              },
              optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
              quantity: 2,
              images: ['https://res.cloudinary.com/your_cloud_name/image/upload/image1.jpg'],
            },
          ],
          subtotal: 200000,
          discount: 0,
          total: 200000,
          coupon: null,
          address: {
            addressLine: '123 Đường Láng',
            ward: 'Phường 1',
            district: 'Quận 1',
            cityOrProvince: 'TP.HCM',
          },
          sdt: '0123456789',
          paymentMethod: 'cod',
          paymentStatus: 'failed',
          shippingStatus: 'failed',
          returnStatus: 'none',
          returnRequestDate: null,
          returnReason: null,
          returnImages: [],
          returnVideos: [],
          note: 'Giao hàng nhanh',
          cancelReason: null,
          cancelNote: null,
          cancelledAt: null,
          cancelledBy: null,
          failReason: 'delivery_error',
          confirmedAt: null,
          createdAt: '2025-07-09T10:18:00Z',
          updatedAt: '2025-07-10T10:18:00Z',
        },
      ],
    },
    errorResponses: [
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database hoặc lỗi populate' },
    ],
  },
  {
    method: 'GET',
    path: '/api/orders/user/:userId',
    description: 'Lấy danh sách đơn hàng của người dùng',
    fullDescription: 'Trả về danh sách đơn hàng của một người dùng dựa trên `userId`, sắp xếp theo ID (`_id`) giảm dần. Chỉ trả về các đơn hàng của người dùng đang đăng nhập (kiểm tra qua token). Bao gồm thông tin sản phẩm (`items.product`) được populate. Yêu cầu xác thực thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của người dùng được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'userId',
        type: 'string',
        description: 'ObjectId của người dùng (phải khớp với userId trong token)',
        required: true,
        in: 'path',
      },
    ],
    response: {
      status: 200,
      description: 'Danh sách đơn hàng của người dùng',
      example: [
        {
          _id: '60d5f8e9b1a2b4f8e8f9e2c7',
          user: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b0',
            username: 'user1',
            email: 'user1@example.com',
          },
          items: [
            {
              product: {
                _id: '60d5f8e9b1a2b4f8e8f9e2b1',
                name: 'Sản phẩm A',
                price: 100000,
                image: 'https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg',
              },
              optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
              quantity: 2,
              images: ['https://res.cloudinary.com/your_cloud_name/image/upload/image1.jpg'],
            },
          ],
          subtotal: 200000,
          discount: 0,
          total: 200000,
          coupon: null,
          address: {
            addressLine: '123 Đường Láng',
            ward: 'Phường 1',
            district: 'Quận 1',
            cityOrProvince: 'TP.HCM',
          },
          sdt: '0123456789',
          paymentMethod: 'cod',
          paymentStatus: 'pending',
          shippingStatus: 'pending',
          returnStatus: 'none',
          returnRequestDate: null,
          returnReason: null,
          returnImages: [],
          returnVideos: [],
          note: 'Giao hàng nhanh',
          cancelReason: null,
          cancelNote: null,
          cancelledAt: null,
          cancelledBy: null,
          failReason: null,
          confirmedAt: null,
          createdAt: '2025-07-09T10:18:00Z',
          updatedAt: '2025-07-09T10:18:00Z',
        },
      ],
    },
    errorResponses: [
      { status: 400, description: 'Thiếu userId hoặc userId không hợp lệ' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 404, description: 'Người dùng không tồn tại' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database hoặc lỗi populate' },
    ],
  },
  {
    method: 'GET',
    path: '/api/orders/order/:orderId',
    description: 'Lấy chi tiết đơn hàng',
    fullDescription: 'Trả về chi tiết một đơn hàng dựa trên `orderId`, chỉ trả về nếu đơn hàng thuộc về người dùng đang đăng nhập (kiểm tra qua token). Bao gồm thông tin sản phẩm (`items.product`) và người dùng (`user`) được populate. Yêu cầu xác thực thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của người dùng được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'orderId',
        type: 'string',
        description: 'ObjectId của đơn hàng',
        required: true,
        in: 'path',
      },
    ],
    response: {
      status: 200,
      description: 'Chi tiết đơn hàng',
      example: {
        _id: '60d5f8e9b1a2b4f8e8f9e2c7',
        user: {
          _id: '60d5f8e9b1a2b4f8e8f9e2b0',
          username: 'user1',
          email: 'user1@example.com',
        },
        items: [
          {
            product: {
              _id: '60d5f8e9b1a2b4f8e8f9e2b1',
              name: 'Sản phẩm A',
              price: 100000,
              image: 'https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg',
            },
            optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
            quantity: 2,
            images: ['https://res.cloudinary.com/your_cloud_name/image/upload/image1.jpg'],
          },
        ],
        subtotal: 200000,
        discount: 0,
        total: 200000,
        coupon: null,
        address: {
          addressLine: '123 Đường Láng',
          ward: 'Phường 1',
          district: 'Quận 1',
          cityOrProvince: 'TP.HCM',
        },
        sdt: '0123456789',
        paymentMethod: 'cod',
        paymentStatus: 'pending',
        shippingStatus: 'pending',
        returnStatus: 'none',
        returnRequestDate: null,
        returnReason: null,
        returnImages: [],
        returnVideos: [],
        note: 'Giao hàng nhanh',
        cancelReason: null,
        cancelNote: null,
        cancelledAt: null,
        cancelledBy: null,
        failReason: null,
        confirmedAt: null,
        createdAt: '2025-07-09T10:18:00Z',
        updatedAt: '2025-07-09T10:18:00Z',
      },
    },
    errorResponses: [
      { status: 400, description: 'Thiếu orderId hoặc orderId không hợp lệ' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 404, description: 'Không tìm thấy đơn hàng hoặc đơn hàng không thuộc về người dùng' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database hoặc lỗi populate' },
    ],
  },
  {
    method: 'PUT',
    path: '/api/orders/status/:orderId',
    description: 'Cập nhật trạng thái thanh toán đơn hàng',
    fullDescription: 'Cập nhật trạng thái thanh toán (`paymentStatus`) của một đơn hàng dựa trên `orderId`. Trạng thái hợp lệ: `pending`, `completed`, `failed`, `cancelled`. Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'orderId',
        type: 'string',
        description: 'ObjectId của đơn hàng',
        required: true,
        in: 'path',
      },
      {
        name: 'userId',
        type: 'string',
        description: 'ObjectId của người dùng (truyền qua query hoặc body)',
        required: true,
        in: 'query',
      },
      {
        name: 'paymentStatus',
        type: 'string',
        description: 'Trạng thái thanh toán mới (`pending`, `completed`, `failed`, `cancelled`)',
        required: true,
        in: 'body',
      },
    ],
    requestExample: {
      headers: { Authorization: 'Bearer <token>' },
      query: { userId: '60d5f8e9b1a2b4f8e8f9e2b0' },
      body: {
        paymentStatus: 'completed',
      },
    },
    response: {
      status: 200,
      description: 'Cập nhật trạng thái thanh toán thành công',
      example: {
        message: 'Cập nhật trạng thái thanh toán thành công',
        order: {
          _id: '60d5f8e9b1a2b4f8e8f9e2c7',
          user: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b0',
            username: 'user1',
            email: 'user1@example.com',
          },
          items: [
            {
              product: {
                _id: '60d5f8e9b1a2b4f8e8f9e2b1',
                name: 'Sản phẩm A',
                price: 100000,
                image: 'https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg',
              },
              optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
              quantity: 2,
              images: ['https://res.cloudinary.com/your_cloud_name/image/upload/image1.jpg'],
            },
          ],
          subtotal: 200000,
          discount: 0,
          total: 200000,
          coupon: null,
          address: {
            addressLine: '123 Đường Láng',
            ward: 'Phường 1',
            district: 'Quận 1',
            cityOrProvince: 'TP.HCM',
          },
          sdt: '0123456789',
          paymentMethod: 'cod',
          paymentStatus: 'completed',
          shippingStatus: 'pending',
          returnStatus: 'none',
          returnRequestDate: null,
          returnReason: null,
          returnImages: [],
          returnVideos: [],
          note: 'Giao hàng nhanh',
          cancelReason: null,
          cancelNote: null,
          cancelledAt: null,
          cancelledBy: null,
          failReason: null,
          confirmedAt: null,
          createdAt: '2025-07-09T10:18:00Z',
          updatedAt: '2025-07-09T10:20:00Z',
        },
      },
    },
    errorResponses: [
      { status: 400, description: 'Thiếu orderId, userId, orderId không hợp lệ, hoặc trạng thái thanh toán không hợp lệ' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 404, description: 'Không tìm thấy đơn hàng hoặc người dùng' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database hoặc lỗi populate' },
    ],
  },
  {
    method: 'PUT',
    path: '/api/orders/update/:orderId',
    description: 'Cập nhật thông tin đơn hàng',
    fullDescription: 'Cập nhật thông tin đơn hàng dựa trên `orderId`, bao gồm các trường như trạng thái vận chuyển (`shippingStatus`), trạng thái thanh toán (`paymentStatus`), trạng thái hoàn hàng (`returnStatus`), lý do hủy (`cancelReason`), lý do thất bại (`failReason`), địa chỉ giao hàng (`address`), danh sách sản phẩm (`items`), và tổng tiền (`total`). Nếu trạng thái vận chuyển chuyển sang `cancelled`, `failed`, hoặc `returned`, hệ thống sẽ khôi phục số lượng hàng trong kho. Gửi email thông báo nếu trạng thái là `failed`. Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'orderId',
        type: 'string',
        description: 'ObjectId của đơn hàng',
        required: true,
        in: 'path',
      },
      {
        name: 'shippingStatus',
        type: 'string',
        description: 'Trạng thái vận chuyển mới (`pending`, `confirmed`, `in_transit`, `delivered`, `returned`, `cancelled`, `failed`)',
        required: false,
        in: 'body',
      },
      {
        name: 'paymentStatus',
        type: 'string',
        description: 'Trạng thái thanh toán mới (`pending`, `completed`, `failed`, `cancelled`)',
        required: false,
        in: 'body',
      },
      {
        name: 'returnStatus',
        type: 'string',
        description: 'Trạng thái hoàn hàng mới (`none`, `requested`, `approved`, `rejected`)',
        required: false,
        in: 'body',
      },
      {
        name: 'cancelReason',
        type: 'string',
        description: 'Lý do hủy đơn hàng (`Đổi ý không mua nữa`, `Muốn thay đổi sản phẩm`, `Thay đổi phương thức thanh toán`, `Thay đổi địa chỉ giao hàng`, `Lý do khác`, `out_of_stock`, `customer_cancelled`, `system_error`, `other`)',
        required: false,
        in: 'body',
      },
      {
        name: 'failReason',
        type: 'string',
        description: 'Lý do giao hàng thất bại (`delivery_error`, `address_issue`, `timeout`, `other`)',
        required: false,
        in: 'body',
      },
      {
        name: 'address',
        type: 'object',
        description: 'Địa chỉ giao hàng mới (object chứa addressLine, ward, district, cityOrProvince)',
        required: false,
        in: 'body',
      },
      {
        name: 'items',
        type: 'array',
        description: 'Danh sách sản phẩm mới (mỗi phần tử chứa product, optionId, quantity, images)',
        required: false,
        in: 'body',
      },
      {
        name: 'total',
        type: 'number',
        description: 'Tổng tiền mới (phải không âm)',
        required: false,
        in: 'body',
      },
    ],
    requestExample: {
      headers: { Authorization: 'Bearer <token>' },
      body: {
        shippingStatus: 'delivered',
        paymentStatus: 'completed',
        total: 250000,
        address: {
          addressLine: '456 Đường Láng',
          ward: 'Phường 2',
          district: 'Quận 1',
          cityOrProvince: 'TP.HCM',
        },
        items: [
          {
            product: '60d5f8e9b1a2b4f8e8f9e2b1',
            optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
            quantity: 3,
            images: ['https://res.cloudinary.com/your_cloud_name/image/upload/image1.jpg'],
          },
        ],
      },
    },
    response: {
      status: 200,
      description: 'Cập nhật đơn hàng thành công',
      example: {
        message: 'Cập nhật đơn hàng thành công',
        order: {
          _id: '60d5f8e9b1a2b4f8e8f9e2c7',
          user: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b0',
            username: 'user1',
            email: 'user1@example.com',
          },
          items: [
            {
              product: {
                _id: '60d5f8e9b1a2b4f8e8f9e2b1',
                name: 'Sản phẩm A',
                price: 100000,
                image: 'https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg',
              },
              optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
              quantity: 3,
              images: ['https://res.cloudinary.com/your_cloud_name/image/upload/image1.jpg'],
            },
          ],
          subtotal: 300000,
          discount: 0,
          total: 250000,
          coupon: null,
          address: {
            addressLine: '456 Đường Láng',
            ward: 'Phường 2',
            district: 'Quận 1',
            cityOrProvince: 'TP.HCM',
          },
          sdt: '0123456789',
          paymentMethod: 'cod',
          paymentStatus: 'completed',
          shippingStatus: 'delivered',
          returnStatus: 'none',
          returnRequestDate: null,
          returnReason: null,
          returnImages: [],
          returnVideos: [],
          note: 'Giao hàng nhanh',
          cancelReason: null,
          cancelNote: null,
          cancelledAt: null,
          cancelledBy: null,
          failReason: null,
          confirmedAt: null,
          createdAt: '2025-07-09T10:18:00Z',
          updatedAt: '2025-07-09T10:20:00Z',
        },
        stockRestored: [],
      },
    },
    errorResponses: [
      { status: 400, description: 'Thiếu orderId, orderId không hợp lệ, hoặc dữ liệu cập nhật không hợp lệ (trạng thái, lý do, v.v.)' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 404, description: 'Không tìm thấy đơn hàng' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database, lỗi khôi phục kho, hoặc lỗi gửi email' },
    ],
  },
  {
    method: 'DELETE',
    path: '/api/orders/cancel/:orderId',
    description: 'Hủy đơn hàng',
    fullDescription: 'Hủy một đơn hàng dựa trên `orderId`, chỉ cho phép khi trạng thái vận chuyển (`shippingStatus`) là `pending`. Người dùng chỉ có thể hủy đơn hàng của chính mình, trong khi admin có thể hủy bất kỳ đơn hàng nào. Hệ thống khôi phục số lượng hàng trong kho và gửi email thông báo hủy đơn hàng tới người dùng. Yêu cầu xác thực thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của người dùng hoặc admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'orderId',
        type: 'string',
        description: 'ObjectId của đơn hàng',
        required: true,
        in: 'path',
      },
      {
        name: 'cancelReason',
        type: 'string',
        description: 'Lý do hủy đơn hàng (`Đổi ý không mua nữa`, `Muốn thay đổi sản phẩm`, `Thay đổi phương thức thanh toán`, `Thay đổi địa chỉ giao hàng`, `Lý do khác`, `out_of_stock`, `customer_cancelled`, `system_error`, `other`)',
        required: true,
        in: 'body',
      },
      {
        name: 'cancelNote',
        type: 'string',
        description: 'Ghi chú hủy đơn hàng (tùy chọn)',
        required: false,
        in: 'body',
      },
    ],
    requestExample: {
      headers: { Authorization: 'Bearer <token>' },
      body: {
        cancelReason: 'Đổi ý không mua nữa',
        cancelNote: 'Không cần sản phẩm này nữa',
      },
    },
    response: {
      status: 200,
      description: 'Hủy đơn hàng thành công',
      example: {
        message: 'Hủy đơn hàng thành công',
        order: {
          _id: '60d5f8e9b1a2b4f8e8f9e2c7',
          user: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b0',
            username: 'user1',
            email: 'user1@example.com',
          },
          items: [
            {
              product: {
                _id: '60d5f8e9b1a2b4f8e8f9e2b1',
                name: 'Sản phẩm A',
                price: 100000,
                image: 'https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg',
              },
              optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
              quantity: 2,
              images: ['https://res.cloudinary.com/your_cloud_name/image/upload/image1.jpg'],
            },
          ],
          subtotal: 200000,
          discount: 0,
          total: 200000,
          coupon: null,
          address: {
            addressLine: '123 Đường Láng',
            ward: 'Phường 1',
            district: 'Quận 1',
            cityOrProvince: 'TP.HCM',
          },
          sdt: '0123456789',
          paymentMethod: 'cod',
          paymentStatus: 'cancelled',
          shippingStatus: 'cancelled',
          returnStatus: 'none',
          returnRequestDate: null,
          returnReason: null,
          returnImages: [],
          returnVideos: [],
          note: 'Giao hàng nhanh',
          cancelReason: 'Đổi ý không mua nữa',
          cancelNote: 'Không cần sản phẩm này nữa',
          cancelledAt: '2025-07-09T10:20:00Z',
          cancelledBy: '60d5f8e9b1a2b4f8e8f9e2b0',
          failReason: null,
          confirmedAt: null,
          createdAt: '2025-07-09T10:18:00Z',
          updatedAt: '2025-07-09T10:20:00Z',
        },
        stockRestored: [
          {
            productId: '60d5f8e9b1a2b4f8e8f9e2b1',
            optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
            quantity: 2,
            variantValue: 'Màu đỏ',
          },
        ],
      },
    },
    errorResponses: [
      { status: 400, description: 'Thiếu orderId, orderId không hợp lệ, thiếu lý do hủy, lý do hủy không hợp lệ, hoặc không thể hủy do trạng thái không phải `pending`' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Người dùng không có quyền hủy đơn hàng này' },
      { status: 404, description: 'Không tìm thấy đơn hàng' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database, lỗi khôi phục kho, hoặc lỗi gửi email' },
    ],
  },
  {
    method: 'POST',
    path: '/api/orders/return/:orderId',
    description: 'Yêu cầu hoàn hàng',
    fullDescription: 'Gửi yêu cầu hoàn hàng cho một đơn hàng dựa trên `orderId`, chỉ cho phép khi đơn hàng ở trạng thái `delivered` và trong vòng 3-4 ngày kể từ khi đặt hàng. Yêu cầu lý do hoàn hàng và có thể đính kèm tối đa 5 ảnh (`jpg`, `jpeg`, `png`, `gif`, `webp`, `svg`) và 1 video (`mp4`, `mpeg`, `mov`, `webm`) qua `multipart/form-data`. Chỉ người dùng sở hữu đơn hàng có thể gửi yêu cầu. Gửi email thông báo tới người dùng. Yêu cầu xác thực thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của người dùng được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'orderId',
        type: 'string',
        description: 'ObjectId của đơn hàng',
        required: true,
        in: 'path',
      },
      {
        name: 'returnReason',
        type: 'string',
        description: 'Lý do yêu cầu hoàn hàng',
        required: true,
        in: 'formData',
      },
      {
        name: 'returnImages',
        type: 'file',
        description: 'File ảnh đính kèm (jpg, jpeg, png, gif, webp, svg; tối đa 5 file, mỗi file 100MB, tùy chọn)',
        required: false,
        in: 'formData',
      },
      {
        name: 'orderVideo',
        type: 'file',
        description: 'File video đính kèm (mp4, mpeg, mov, webm; tối đa 1 file, 100MB, tùy chọn)',
        required: false,
        in: 'formData',
      },
    ],
    requestExample: {
      headers: { Authorization: 'Bearer <token>', 'Content-Type': 'multipart/form-data' },
      body: {
        returnReason: 'Sản phẩm bị lỗi',
        returnImages: ['image1.jpg', 'image2.jpg'],
        orderVideo: ['video1.mp4'],
      },
    },
    response: {
      status: 200,
      description: 'Yêu cầu hoàn hàng thành công',
      example: {
        message: 'Yêu cầu hoàn hàng đã được gửi thành công',
        order: {
          _id: '60d5f8e9b1a2b4f8e8f9e2c7',
          user: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b0',
            username: 'user1',
            email: 'user1@example.com',
          },
          items: [
            {
              product: {
                _id: '60d5f8e9b1a2b4f8e8f9e2b1',
                name: 'Sản phẩm A',
                price: 100000,
                image: 'https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg',
              },
              optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
              quantity: 2,
              images: ['https://res.cloudinary.com/your_cloud_name/image/upload/image1.jpg'],
            },
          ],
          subtotal: 200000,
          discount: 0,
          total: 200000,
          coupon: null,
          address: {
            addressLine: '123 Đường Láng',
            ward: 'Phường 1',
            district: 'Quận 1',
            cityOrProvince: 'TP.HCM',
          },
          sdt: '0123456789',
          paymentMethod: 'cod',
          paymentStatus: 'completed',
          shippingStatus: 'delivered',
          returnStatus: 'requested',
          returnRequestDate: '2025-07-10T10:18:00Z',
          returnReason: 'Sản phẩm bị lỗi',
          returnImages: [
            { url: 'https://res.cloudinary.com/your_cloud_name/image/upload/return1.jpg', public_id: 'return1' },
            { url: 'https://res.cloudinary.com/your_cloud_name/image/upload/return2.jpg', public_id: 'return2' },
          ],
          returnVideos: [
            { url: 'https://res.cloudinary.com/your_cloud_name/video/upload/video1.mp4', public_id: 'video1' },
          ],
          note: 'Giao hàng nhanh',
          cancelReason: null,
          cancelNote: null,
          cancelledAt: null,
          cancelledBy: null,
          failReason: null,
          confirmedAt: null,
          createdAt: '2025-07-09T10:18:00Z',
          updatedAt: '2025-07-10T10:18:00Z',
        },
      },
    },
    errorResponses: [
      { status: 400, description: 'Thiếu orderId, orderId không hợp lệ, thiếu lý do hoàn hàng, đơn hàng không ở trạng thái `delivered`, vượt quá thời hạn 3-4 ngày, hoặc file ảnh/video không hợp lệ' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Người dùng không có quyền yêu cầu hoàn hàng này' },
      { status: 404, description: 'Không tìm thấy đơn hàng' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database, Cloudinary, hoặc lỗi gửi email' },
    ],
  },
  {
    method: 'PUT',
    path: '/api/orders/admin/return/:orderId',
    description: 'Xác nhận yêu cầu hoàn hàng (admin)',
    fullDescription: 'Xác nhận hoặc từ chối yêu cầu hoàn hàng cho một đơn hàng dựa trên `orderId`. Trạng thái hoàn hàng (`returnStatus`) có thể được cập nhật thành `approved` hoặc `rejected`. Nếu `approved`, trạng thái vận chuyển (`shippingStatus`) được cập nhật thành `returned`, trạng thái thanh toán (`paymentStatus`) được cập nhật thành `cancelled`, và số lượng hàng được khôi phục về kho. Gửi email thông báo tới người dùng. Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'orderId',
        type: 'string',
        description: 'ObjectId của đơn hàng',
        required: true,
        in: 'path',
      },
      {
        name: 'returnStatus',
        type: 'string',
        description: 'Trạng thái hoàn hàng mới (`approved` hoặc `rejected`)',
        required: true,
        in: 'body',
      },
    ],
    requestExample: {
      headers: { Authorization: 'Bearer <token>' },
      body: {
        returnStatus: 'approved',
      },
    },
    response: {
      status: 200,
      description: 'Xác nhận yêu cầu hoàn hàng thành công',
      example: {
        message: 'Yêu cầu hoàn hàng đã được chấp nhận',
        order: {
          _id: '60d5f8e9b1a2b4f8e8f9e2c7',
          user: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b0',
            username: 'user1',
            email: 'user1@example.com',
          },
          items: [
            {
              product: {
                _id: '60d5f8e9b1a2b4f8e8f9e2b1',
                name: 'Sản phẩm A',
                price: 100000,
                image: 'https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg',
              },
              optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
              quantity: 2,
              images: ['https://res.cloudinary.com/your_cloud_name/image/upload/image1.jpg'],
            },
          ],
          subtotal: 200000,
          discount: 0,
          total: 200000,
          coupon: null,
          address: {
            addressLine: '123 Đường Láng',
            ward: 'Phường 1',
            district: 'Quận 1',
            cityOrProvince: 'TP.HCM',
          },
          sdt: '0123456789',
          paymentMethod: 'cod',
          paymentStatus: 'cancelled',
          shippingStatus: 'returned',
          returnStatus: 'approved',
          returnRequestDate: '2025-07-10T10:18:00Z',
          returnReason: 'Sản phẩm bị lỗi',
          returnImages: [
            { url: 'https://res.cloudinary.com/your_cloud_name/image/upload/return1.jpg', public_id: 'return1' },
            { url: 'https://res.cloudinary.com/your_cloud_name/image/upload/return2.jpg', public_id: 'return2' },
          ],
          returnVideos: [
            { url: 'https://res.cloudinary.com/your_cloud_name/video/upload/video1.mp4', public_id: 'video1' },
          ],
          note: 'Giao hàng nhanh',
          cancelReason: null,
          cancelNote: null,
          cancelledAt: null,
          cancelledBy: null,
          failReason: null,
          confirmedAt: null,
          createdAt: '2025-07-09T10:18:00Z',
          updatedAt: '2025-07-10T10:20:00Z',
        },
        emailStatus: 'Email sent successfully',
        stockRestored: [
          {
            productId: '60d5f8e9b1a2b4f8e8f9e2b1',
            optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
            quantity: 2,
            variantValue: 'Màu đỏ',
          },
        ],
      },
    },
    errorResponses: [
      { status: 400, description: 'Thiếu orderId, orderId không hợp lệ, trạng thái hoàn hàng không hợp lệ, hoặc đơn hàng không ở trạng thái `requested`' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 404, description: 'Không tìm thấy đơn hàng' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database, lỗi khôi phục kho, hoặc lỗi gửi email' },
    ],
  },
  {
    method: 'PUT',
    path: '/api/orders/admin/fail/:orderId',
    description: 'Đánh dấu đơn hàng giao thất bại (admin)',
    fullDescription: 'Đánh dấu một đơn hàng là giao thất bại (`shippingStatus: failed`, `paymentStatus: failed`) dựa trên `orderId`. Yêu cầu cung cấp lý do thất bại (`failReason`). Hệ thống khôi phục số lượng hàng trong kho và gửi email thông báo tới người dùng. Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'orderId',
        type: 'string',
        description: 'ObjectId của đơn hàng',
        required: true,
        in: 'path',
      },
      {
        name: 'failReason',
        type: 'string',
        description: 'Lý do giao hàng thất bại (`delivery_error`, `address_issue`, `timeout`, `other`)',
        required: true,
        in: 'body',
      },
    ],
    requestExample: {
      headers: { Authorization: 'Bearer <token>' },
      body: {
        failReason: 'delivery_error',
      },
    },
    response: {
      status: 200,
      description: 'Đánh dấu đơn hàng giao thất bại thành công',
      example: {
        message: 'Đã đánh dấu đơn hàng giao thất bại',
        order: {
          _id: '60d5f8e9b1a2b4f8e8f9e2c7',
          user: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b0',
            username: 'user1',
            email: 'user1@example.com',
          },
          items: [
            {
              product: {
                _id: '60d5f8e9b1a2b4f8e8f9e2b1',
                name: 'Sản phẩm A',
                price: 100000,
                image: 'https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg',
              },
              optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
              quantity: 2,
              images: ['https://res.cloudinary.com/your_cloud_name/image/upload/image1.jpg'],
            },
          ],
          subtotal: 200000,
          discount: 0,
          total: 200000,
          coupon: null,
          address: {
            addressLine: '123 Đường Láng',
            ward: 'Phường 1',
            district: 'Quận 1',
            cityOrProvince: 'TP.HCM',
          },
          sdt: '0123456789',
          paymentMethod: 'cod',
          paymentStatus: 'failed',
          shippingStatus: 'failed',
          returnStatus: 'none',
          returnRequestDate: null,
          returnReason: null,
          returnImages: [],
          returnVideos: [],
          note: 'Giao hàng nhanh',
          cancelReason: null,
          cancelNote: null,
          cancelledAt: null,
          cancelledBy: null,
          failReason: 'delivery_error',
          confirmedAt: null,
          createdAt: '2025-07-09T10:18:00Z',
          updatedAt: '2025-07-09T10:20:00Z',
        },
        stockRestored: [
          {
            productId: '60d5f8e9b1a2b4f8e8f9e2b1',
            optionId: '60d5f8e9b1a2b4f8e8f9e2b2',
            quantity: 2,
            variantValue: 'Màu đỏ',
          },
        ],
      },
    },
    errorResponses: [
      { status: 400, description: 'Thiếu orderId, orderId không hợp lệ, hoặc thiếu lý do thất bại' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 404, description: 'Không tìm thấy đơn hàng' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database, lỗi khôi phục kho, hoặc lỗi gửi email' },
    ],
  },
];

export default orderEndpoints;