const productEndpoints = [
  {
    method: 'GET',
    path: '/api/products',
    description: 'Lấy tất cả sản phẩm (chỉ admin)',
    fullDescription:
      'Trả về danh sách tất cả sản phẩm, bao gồm cả sản phẩm ẩn (`hidden`) và không hoạt động (`inactive`). Populates `id_category` để tính `isActive` (dựa trên `product.active` và `category.status`). Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description:
        'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [],
    response: {
      status: 200,
      description: 'Danh sách tất cả sản phẩm',
      example: [
        {
          _id: '60d5f8e9b1a2b4f8e8f9e2b1',
          name: 'Sản phẩm 1',
          slug: 'san-pham-1',
          status: 'show',
          active: true,
          isActive: true,
          view: 100,
          id_brand: '60d5f8e9b1a2b4f8e8f9e2b2',
          id_category: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b3',
            status: 'show',
          },
          images: ['https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg'],
          short_description: 'Mô tả ngắn',
          description: 'Mô tả chi tiết',
          option: [{ value: 'Size M', price: 100000, stock: 50 }],
          createdAt: '2025-07-17T12:12:00.000Z',
          updatedAt: '2025-07-17T12:12:00.000Z',
        },
      ],
    },
    errorResponses: [
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database' },
    ],
  },
  {
    method: 'GET',
    path: '/api/products/active',
    description: 'Lấy sản phẩm đang hoạt động',
    fullDescription:
      'Trả về danh sách các sản phẩm có `status: show` và `isActive: true` (dựa trên `product.active` và `category.status: show`). Populates `id_category` để tính `isActive`. Không yêu cầu xác thực, endpoint này công khai.',
    auth: {
      required: false,
      description: 'Không yêu cầu token. Endpoint này có thể truy cập công khai.',
    },
    parameters: [],
    response: {
      status: 200,
      description: 'Danh sách sản phẩm đang hoạt động',
      example: [
        {
          _id: '60d5f8e9b1a2b4f8e8f9e2b1',
          name: 'Sản phẩm 1',
          slug: 'san-pham-1',
          status: 'show',
          active: true,
          isActive: true,
          view: 100,
          id_brand: '60d5f8e9b1a2b4f8e8f9e2b2',
          id_category: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b3',
            status: 'show',
          },
          images: ['https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg'],
          short_description: 'Mô tả ngắn',
          description: 'Mô tả chi tiết',
          option: [{ value: 'Size M', price: 100000, stock: 50 }],
          createdAt: '2025-07-17T12:12:00.000Z',
          updatedAt: '2025-07-17T12:12:00.000Z',
        },
      ],
    },
    errorResponses: [
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database' },
    ],
  },
  {
    method: 'GET',
    path: '/api/products/:identifier',
    description: 'Lấy sản phẩm theo ID hoặc slug',
    fullDescription:
      'Trả về thông tin chi tiết của một sản phẩm dựa trên `identifier` (ID hoặc slug). Nếu không có token admin (người dùng thường), lượt xem (`view`) tăng lên 1. Populates `id_category` để tính `isActive`. Endpoint này công khai, token admin tùy chọn.',
    auth: {
      required: false,
      header: 'Authorization: Bearer <token>',
      description:
        'Token JWT tùy chọn. Nếu cung cấp token admin, lượt xem không tăng. Nếu không, lượt xem tăng lên.',
    },
    parameters: [
      {
        name: 'identifier',
        type: 'string',
        description: 'ObjectId hoặc slug của sản phẩm',
        required: true,
        in: 'path',
      },
    ],
    response: {
      status: 200,
      description: 'Chi tiết sản phẩm',
      example: {
        _id: '60d5f8e9b1a2b4f8e8f9e2b1',
        name: 'Sản phẩm 1',
        slug: 'san-pham-1',
        status: 'show',
        active: true,
        isActive: true,
        view: 101,
        id_brand: '60d5f8e9b1a2b4f8e8f9e2b2',
        id_category: {
          _id: '60d5f8e9b1a2b4f8e8f9e2b3',
          status: 'show',
        },
        images: ['https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg'],
        short_description: 'Mô tả ngắn',
        description: 'Mô tả chi tiết',
        option: [{ value: 'Size M', price: 100000, stock: 50 }],
        createdAt: '2025-07-17T12:12:00.000Z',
        updatedAt: '2025-07-17T12:12:00.000Z',
      },
    },
    errorResponses: [
      { status: 400, description: 'Identifier không hợp lệ' },
      { status: 404, description: 'Không tìm thấy sản phẩm' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database' },
    ],
  },
  {
    method: 'POST',
    path: '/api/products',
    description: 'Tạo sản phẩm mới',
    fullDescription:
      'Tạo một sản phẩm mới với các thông tin được cung cấp. Yêu cầu quyền admin thông qua token JWT. Hỗ trợ upload nhiều file ảnh lên Cloudinary, thay thế danh sách ảnh hiện tại. Tên sản phẩm phải duy nhất (không phân biệt hoa thường). Slug được tự động tạo từ tên sản phẩm và đảm bảo tính duy nhất. Dữ liệu gửi qua `multipart/form-data`.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'name',
        type: 'string',
        description: 'Tên sản phẩm, phải duy nhất (không phân biệt hoa thường)',
        required: true,
        in: 'body',
      },
      {
        name: 'id_brand',
        type: 'string',
        description: 'ObjectId của thương hiệu, phải tồn tại trong database',
        required: true,
        in: 'body',
      },
      {
        name: 'id_category',
        type: 'string',
        description: 'ObjectId của danh mục, phải tồn tại trong database',
        required: true,
        in: 'body',
      },
      {
        name: 'status',
        type: 'string',
        description: 'Trạng thái hiển thị (`show` hoặc `hidden`), mặc định là `show`',
        required: false,
        in: 'body',
      },
      {
        name: 'active',
        type: 'boolean',
        description: 'Trạng thái hoạt động, mặc định là `true`',
        required: false,
        in: 'body',
      },
      {
        name: 'view',
        type: 'number',
        description: 'Số lượt xem, mặc định là `0`',
        required: false,
        in: 'body',
      },
      {
        name: 'short_description',
        type: 'string',
        description: 'Mô tả ngắn của sản phẩm',
        required: false,
        in: 'body',
      },
      {
        name: 'description',
        type: 'string',
        description: 'Mô tả chi tiết của sản phẩm',
        required: false,
        in: 'body',
      },
      {
        name: 'option',
        type: 'string',
        description:
          'Danh sách tùy chọn sản phẩm (JSON string), mỗi tùy chọn phải có `value` (string), `price` (number, không âm), `stock` (number, không âm), và tùy chọn `discount_price` (number, không âm). Ví dụ: `[{value: "Size M", price: 100000, stock: 50}]`',
        required: false,
        in: 'body',
      },
      {
        name: 'images',
        type: 'file',
        description: 'File ảnh sản phẩm (hỗ trợ nhiều file, định dạng: jpg, jpeg, png, gif, webp, svg; tối đa 20MB mỗi file)',
        required: false,
        in: 'formData',
      },
    ],
    requestExample: {
      headers: { Authorization: 'Bearer <token>', 'Content-Type': 'multipart/form-data' },
      body: {
        name: 'Sản phẩm 2',
        id_brand: '60d5f8e9b1a2b4f8e8f9e2b2',
        id_category: '60d5f8e9b1a2b4f8e8f9e2b3',
        status: 'show',
        active: true,
        view: 0,
        short_description: 'Mô tả ngắn',
        description: 'Mô tả chi tiết',
        option: '[{"value": "Size L", "price": 120000, "stock": 30}]',
      },
      files: ['product2.jpg'],
    },
    response: {
      status: 201,
      description: 'Tạo sản phẩm thành công',
      example: {
        message: 'Tạo sản phẩm thành công',
        product: {
          _id: '60d5f8e9b1a2b4f8e8f9e2b4',
          name: 'Sản phẩm 2',
          slug: 'san-pham-2',
          status: 'show',
          active: true,
          isActive: true,
          view: 0,
          id_brand: '60d5f8e9b1a2b4f8e8f9e2b2',
          id_category: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b3',
            status: 'show',
          },
          images: ['https://res.cloudinary.com/your_cloud_name/image/upload/product2.jpg'],
          short_description: 'Mô tả ngắn',
          description: 'Mô tả chi tiết',
          option: [{ value: 'Size L', price: 120000, stock: 30 }],
          createdAt: '2025-07-17T12:12:00.000Z',
          updatedAt: '2025-07-17T12:12:00.000Z',
        },
      },
    },
    errorResponses: [
      { status: 400, description: 'Thiếu các trường bắt buộc: name, id_brand, id_category' },
      { status: 400, description: 'Tên sản phẩm đã tồn tại (không phân biệt hoa thường)' },
      { status: 400, description: 'id_brand hoặc id_category không hợp lệ hoặc không tồn tại' },
      { status: 400, description: 'Dữ liệu option không hợp lệ (JSON sai cú pháp hoặc thiếu value, price, stock)' },
      { status: 400, description: 'Trùng lặp slug' },
      { status: 400, description: 'Chỉ hỗ trợ file ảnh (jpg, jpeg, png, gif, webp, svg) cho images' },
      { status: 400, description: 'Kích thước file ảnh vượt quá 20MB' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database hoặc Cloudinary' },
    ],
  },
  {
    method: 'PUT',
    path: '/api/products/:identifier',
    description: 'Cập nhật sản phẩm',
    fullDescription:
      'Cập nhật thông tin sản phẩm dựa trên `identifier` (ID hoặc slug). Yêu cầu quyền admin thông qua token JWT. Hỗ trợ upload ảnh mới lên Cloudinary, thay thế danh sách ảnh hiện tại. Tên sản phẩm mới phải duy nhất (không phân biệt hoa thường) và tự động tạo slug mới nếu thay đổi. Dữ liệu gửi qua `multipart/form-data`.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'identifier',
        type: 'string',
        description: 'ObjectId hoặc slug của sản phẩm',
        required: true,
        in: 'path',
      },
      {
        name: 'name',
        type: 'string',
        description: 'Tên sản phẩm mới, phải duy nhất (không phân biệt hoa thường), tự động tạo slug mới nếu thay đổi',
        required: false,
        in: 'body',
      },
      {
        name: 'id_brand',
        type: 'string',
        description: 'ObjectId của thương hiệu, phải tồn tại trong database',
        required: false,
        in: 'body',
      },
      {
        name: 'id_category',
        type: 'string',
        description: 'ObjectId của danh mục, phải tồn tại trong database',
        required: false,
        in: 'body',
      },
      {
        name: 'status',
        type: 'string',
        description: 'Trạng thái hiển thị (`show` hoặc `hidden`)',
        required: false,
        in: 'body',
      },
      {
        name: 'active',
        type: 'boolean',
        description: 'Trạng thái hoạt động',
        required: false,
        in: 'body',
      },
      {
        name: 'view',
        type: 'number',
        description: 'Số lượt xem mới',
        required: false,
        in: 'body',
      },
      {
        name: 'short_description',
        type: 'string',
        description: 'Mô tả ngắn mới',
        required: false,
        in: 'body',
      },
      {
        name: 'description',
        type: 'string',
        description: 'Mô tả chi tiết mới',
        required: false,
        in: 'body',
      },
      {
        name: 'option',
        type: 'string',
        description:
          'Danh sách tùy chọn sản phẩm mới (JSON string), mỗi tùy chọn phải có `value` (string), `price` (number, không âm), `stock` (number, không âm), và tùy chọn `discount_price` (number, không âm). Ví dụ: `[{value: "Size M", price: 100000, stock: 50}]`',
        required: false,
        in: 'body',
      },
      {
        name: 'images',
        type: 'file',
        description: 'File ảnh mới (hỗ trợ nhiều file, thay thế ảnh cũ, định dạng: jpg, jpeg, png, gif, webp, svg; tối đa 20MB mỗi file)',
        required: false,
        in: 'formData',
      },
    ],
    requestExample: {
      headers: { Authorization: 'Bearer <token>', 'Content-Type': 'multipart/form-data' },
      body: {
        name: 'Sản phẩm 1 (Cập nhật)',
        id_brand: '60d5f8e9b1a2b4f8e8f9e2b2',
        id_category: '60d5f8e9b1a2b4f8e8f9e2b3',
        status: 'show',
        active: true,
        short_description: 'Mô tả ngắn cập nhật',
        description: 'Mô tả chi tiết cập nhật',
        option: '[{"value": "Size M", "price": 110000, "stock": 40}]',
      },
      files: ['product1_updated.jpg'],
    },
    response: {
      status: 200,
      description: 'Cập nhật sản phẩm thành công',
      example: {
        message: 'Cập nhật sản phẩm thành công',
        product: {
          _id: '60d5f8e9b1a2b4f8e8f9e2b1',
          name: 'Sản phẩm 1 (Cập nhật)',
          slug: 'san-pham-1-cap-nhat',
          status: 'show',
          active: true,
          isActive: true,
          view: 101,
          id_brand: '60d5f8e9b1a2b4f8e8f9e2b2',
          id_category: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b3',
            status: 'show',
          },
          images: ['https://res.cloudinary.com/your_cloud_name/image/upload/product1_updated.jpg'],
          short_description: 'Mô tả ngắn cập nhật',
          description: 'Mô tả chi tiết cập nhật',
          option: [{ value: 'Size M', price: 110000, stock: 40 }],
          createdAt: '2025-07-17T12:12:00.000Z',
          updatedAt: '2025-07-17T12:12:00.000Z',
        },
      },
    },
    errorResponses: [
      { status: 400, description: 'Tên sản phẩm đã tồn tại (không phân biệt hoa thường)' },
      { status: 400, description: 'id_brand hoặc id_category không hợp lệ hoặc không tồn tại' },
      { status: 400, description: 'Dữ liệu option không hợp lệ (JSON sai cú pháp hoặc thiếu value, price, stock)' },
      { status: 400, description: 'Trùng lặp slug' },
      { status: 400, description: 'Chỉ hỗ trợ file ảnh (jpg, jpeg, png, gif, webp, svg) cho images' },
      { status: 400, description: 'Kích thước file ảnh vượt quá 20MB' },
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 404, description: 'Không tìm thấy sản phẩm' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database hoặc Cloudinary' },
    ],
  },
  {
    method: 'DELETE',
    path: '/api/products/:identifier',
    description: 'Xóa sản phẩm',
    fullDescription:
      'Xóa một sản phẩm dựa trên `identifier` (ID hoặc slug). Hình ảnh trên Cloudinary không được xóa tự động (quản lý bởi Cloudinary garbage collection). Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'identifier',
        type: 'string',
        description: 'ObjectId hoặc slug của sản phẩm',
        required: true,
        in: 'path',
      },
    ],
    response: {
      status: 200,
      description: 'Xóa sản phẩm thành công',
      example: { message: 'Xóa sản phẩm thành công' },
    },
    errorResponses: [
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 404, description: 'Không tìm thấy sản phẩm' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database' },
    ],
  },
  {
    method: 'PUT',
    path: '/api/products/:identifier/toggle-visibility',
    description: 'Chuyển đổi hiển thị sản phẩm',
    fullDescription:
      'Chuyển đổi trạng thái hiển thị của sản phẩm giữa `show` và `hidden` dựa trên `identifier` (ID hoặc slug). Populates `id_category` để tính `isActive`. Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'identifier',
        type: 'string',
        description: 'ObjectId hoặc slug của sản phẩm',
        required: true,
        in: 'path',
      },
    ],
    response: {
      status: 200,
      description: 'Chuyển đổi trạng thái hiển thị thành công',
      example: {
        message: 'Sản phẩm đã được hiển thị',
        product: {
          _id: '60d5f8e9b1a2b4f8e8f9e2b1',
          name: 'Sản phẩm 1',
          slug: 'san-pham-1',
          status: 'show',
          active: true,
          isActive: true,
          view: 101,
          id_brand: '60d5f8e9b1a2b4f8e8f9e2b2',
          id_category: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b3',
            status: 'show',
          },
          images: ['https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg'],
          short_description: 'Mô tả ngắn',
          description: 'Mô tả chi tiết',
          option: [{ value: 'Size M', price: 100000, stock: 50 }],
          createdAt: '2025-07-17T12:12:00.000Z',
          updatedAt: '2025-07-17T12:12:00.000Z',
        },
      },
    },
    errorResponses: [
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 404, description: 'Không tìm thấy sản phẩm' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database' },
    ],
  },
  {
    method: 'PUT',
    path: '/api/products/:identifier/toggle-active',
    description: 'Chuyển đổi trạng thái hoạt động',
    fullDescription:
      'Chuyển đổi trạng thái hoạt động (`active`) của sản phẩm giữa `true` và `false` dựa trên `identifier` (ID hoặc slug). Populates `id_category` để tính `isActive`. Yêu cầu quyền admin thông qua token JWT.',
    auth: {
      required: true,
      header: 'Authorization: Bearer <token>',
      description: 'Token JWT của admin được yêu cầu trong header. Token được cấp sau khi đăng nhập qua endpoint `/api/users/login`.',
    },
    parameters: [
      {
        name: 'identifier',
        type: 'string',
        description: 'ObjectId hoặc slug của sản phẩm',
        required: true,
        in: 'path',
      },
    ],
    response: {
      status: 200,
      description: 'Chuyển đổi trạng thái hoạt động thành công',
      example: {
        message: 'Sản phẩm đã được kích hoạt',
        product: {
          _id: '60d5f8e9b1a2b4f8e8f9e2b1',
          name: 'Sản phẩm 1',
          slug: 'san-pham-1',
          status: 'show',
          active: true,
          isActive: true,
          view: 101,
          id_brand: '60d5f8e9b1a2b4f8e8f9e2b2',
          id_category: {
            _id: '60d5f8e9b1a2b4f8e8f9e2b3',
            status: 'show',
          },
          images: ['https://res.cloudinary.com/your_cloud_name/image/upload/product1.jpg'],
          short_description: 'Mô tả ngắn',
          description: 'Mô tả chi tiết',
          option: [{ value: 'Size M', price: 100000, stock: 50 }],
          createdAt: '2025-07-17T12:12:00.000Z',
          updatedAt: '2025-07-17T12:12:00.000Z',
        },
      },
    },
    errorResponses: [
      { status: 401, description: 'Không có token hoặc token không hợp lệ' },
      { status: 403, description: 'Không có quyền admin' },
      { status: 404, description: 'Không tìm thấy sản phẩm' },
      { status: 500, description: 'Lỗi máy chủ, có thể do kết nối database' },
    ],
  },
];

export default productEndpoints;